name: ci

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      environment:
        description: "Environment to run tests against"
        type: environment
        required: true
  push:
    branches: ["main"]
    paths:
      - "./**"
  pull_request:
    branches: ["main"]
    paths:
      - "./**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 18
      - name: Build with Maven
        run: mvn clean install
        env:
          BROKER_SERVER: ${{ secrets.BROKER_SERVER }}
          BROKER_SERVER_QUEUE: ${{ secrets.BROKER_SERVER_QUEUE }}
          BROKER_SERVER_PASSWORD: ${{ secrets.BROKER_SERVER_PASSWORD }}
          BROKER_SERVER_USER: ${{ secrets.BROKER_SERVER_USER }}
          SMTP_SERVER_HOST: ${{ secrets.SMTP_SERVER_HOST }}
          SMTP_SERVER_USER: ${{ secrets.SMTP_SERVER_USER }}
          SMTP_SERVER_PASSWORD: ${{ secrets.SMTP_SERVER_PASSWORD }}
          SMTP_SERVER_PORT: ${{ secrets.SMTP_SERVER_PORT }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/service-simple-email-artemismq:${{github.run_number}},${{ secrets.DOCKER_HUB_USERNAME }}/service-simple-email-artemismq:latest
